"""Build portfolio content pages. Articles and isolated demos are maintained separately."""
from pathlib import Path
from html import escape
ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://mobolaji.builtbykora.com'
EMAIL = 'mailto:bjfifi1@gmail.com'
GH = 'https://github.com/korastudios/Kora'

def link(text, href, primary=False):
    return f'<a class="action{" action--primary" if primary else ""}" href="{href}">{text} <span aria-hidden="true">↗</span></a>'

def image(src, alt, cls='', eager=False):
    from PIL import Image
    with Image.open(ROOT/src.lstrip('/')) as im: w,h=im.size
    return f'<img class="{cls}" src="{src}" alt="{escape(alt)}" width="{w}" height="{h}" loading="{"eager" if eager else "lazy"}" decoding="async">'

def page(route, title, description, body):
    nav = ''.join(f'<a href="{url}"'+(' aria-current="page"' if route==url else '')+f'>{label}</a>' for label,url in [('Work','/projects/'),('About','/about/'),('Resume','/assets/resume.pdf'),('Contact',EMAIL)])
    html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} — Mobolaji Ogunbiyi</title><meta name="description" content="{escape(description)}"><meta name="theme-color" content="#ffffff"><link rel="canonical" href="{BASE}{route}"><meta property="og:title" content="{escape(title)} — Mobolaji Ogunbiyi"><meta property="og:description" content="{escape(description)}"><meta property="og:type" content="website"><meta property="og:url" content="{BASE}{route}"><meta property="og:image" content="{BASE}/assets/projects/kora-interactive-sample.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/styles.css?v=rebuild1"><script defer src="/script.js"></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header" data-header><div class="shell header-inner"><a class="wordmark" href="/">Mobolaji Ogunbiyi<span class="wordmark-dot" aria-hidden="true">.</span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="primary-nav" data-menu-button>Menu</button><nav class="primary-nav" id="primary-nav" aria-label="Primary" data-nav>{nav}</nav></div></header>
<main id="main">{body}</main><footer class="site-footer shell"><div><a class="footer-invite" href="{EMAIL}">Let’s build something useful. <span aria-hidden="true">↗</span></a><p>Software engineering & applied AI · Graduating May 2027</p></div><div class="footer-links"><a href="/assets/resume.pdf">Resume</a><a href="https://github.com/Mobi21">GitHub</a><a href="https://www.linkedin.com/in/mobolaji-ogunbiyi-355a53287/">LinkedIn</a><a href="/work-writing/">Writing</a></div><p class="copyright">© 2026 Mobolaji Ogunbiyi · Built with care in Maryland.</p></footer></body></html>'''
    dest=ROOT/route.strip('/')/'index.html'; dest.parent.mkdir(parents=True,exist_ok=True); dest.write_text(html,encoding='utf-8')

def hero(title, desc, meta='', actions=''):
    return f'<section class="project-hero shell"><a class="back-link" href="/projects/">← All work</a><div class="project-heading"><h1>{title}</h1><p class="project-description">{desc}</p></div><div class="project-meta">{meta}</div><div class="action-row">{actions}</div></section>'

def section(title, content, id=''):
    return f'<section class="story-section shell"'+(f' id="{id}"' if id else '')+f'><h2>{title}</h2><div class="story-content">{content}</div></section>'

def ks_preview():
    return '''<div class="ks-preview" aria-label="Illustrated KS App workspace"><div class="ks-sidebar"><b>KS</b><span>Home</span><span class="selected">Projects</span><span>Clients</span><span>Finance</span><span>Knowledge</span></div><div class="ks-preview-main"><div class="ks-topline">Northstar Studio <span>Sample workspace</span></div><h3>Work, moving forward.</h3><div class="ks-preview-row"><b>Website refresh</b><span class="status">In progress</span></div><div class="ks-preview-row"><b>Client onboarding</b><span>In review</span></div><div class="ks-preview-row"><b>Brand guidelines</b><span>Planning</span></div><div class="ks-assistant-note"><span class="assistant-symbol">✦</span><div><b>Your next move, in context.</b><p>Client records, project work, and your AI operator. Together.</p></div></div></div></div>'''

def kora_feature():
    return f'''<article class="feature-kora"><div class="feature-label"><span class="project-logotype">Kora<span class="kora-spark" aria-hidden="true">✳</span></span><span>Personal AI · Windows</span></div><a class="feature-screenshot" href="/projects/kora/">{image('/assets/projects/kora-interactive-sample.png','Interactive Kora sample: fictional conversation and connected project',eager=True)}</a><div class="feature-bottom"><p>An assistant with a place<br>for your context and your work.</p><a class="light-link" href="/projects/kora/">Explore Kora <span aria-hidden="true">↗</span></a></div></article>'''

def work_pair():
    return f'''<div class="work-pair"><article class="feature-ks"><div class="feature-label"><h2>KS App</h2><span>Business software + AI</span></div><a class="preview-link" href="/projects/ks-app/">{ks_preview()}</a><div class="feature-bottom"><p>People and AI.<br>The same workspace.</p><a href="/projects/ks-app/">View project ↗</a></div></article><article class="feature-client"><div class="feature-label"><h2>Built for business.</h2><span>Kora Studio</span></div><a class="client-preview" href="/commercial-work/">{image('/assets/commercial/zubes-grub.webp',"Zube’s Grub: Nigerian-American food website")}</a><div class="feature-bottom"><p>From a customer’s first click<br>to the business behind it.</p><a href="/commercial-work/">See client work ↗</a></div></article></div>'''

home=f'''<div class="home-top shell"><section class="intro"><p class="hello">Hi, I’m Mobolaji <span aria-hidden="true">↗</span></p><h1>I build products.<br><span>And the agents <br>inside them.</span></h1><p class="intro-copy">Software engineer and founder of Kora Studio. I connect thoughtful interfaces, useful AI, and the systems behind them.</p><div class="intro-actions">{link('My work','#work',True)}<a class="text-link" href="/assets/resume.pdf">Resume ↗</a></div><p class="availability">CS + Psychology · May 2027 graduate</p></section>{kora_feature()}</div>
<section class="shell home-work" id="work"><div class="section-heading"><h2>Ideas, made into software.</h2><a class="text-link" href="/projects/">All work ↗</a></div>{work_pair()}</section>
<section class="personal-band shell"><div><p class="hello">A little about me</p><h2>I like connecting<br>the pieces.</h2></div><div><p>Product design and backend systems. Computer science and psychology. A client’s idea and something they can actually use.</p><p>I’ve built software in banking, explored computer vision for ophthalmic imaging, and researched machine learning for power electronics. Today, I’m building Kora and delivering client work through my studio.</p><a class="text-link" href="/about/">More about me ↗</a></div></section>
<section class="award-band shell"><span class="award-mark" aria-hidden="true">✳</span><div><p>TechBuffalo PowerUpTech · First place</p><h2>Good technology meets people where they are.</h2><p>With Seneca Signal, our team brought neighborhood information to a mobile website and SMS interface. We later presented at the Microsoft-sponsored TechConnect 2025 AI for Social Good conference.</p><a class="text-link" href="/about/#seneca">The story behind the win ↗</a></div></section>
<section class="shell notes-section"><div class="section-heading"><h2>Behind the build.</h2><a class="text-link" href="/work-writing/">All writing ↗</a></div><a class="note-row" href="/work-writing/zubes-grub-system/"><span>Client engineering</span><h3>Designing Zube’s Grub</h3><span aria-hidden="true">↗</span></a><a class="note-row" href="/work-writing/kora-runtime/"><span>Agent architecture</span><h3>One runtime, three surfaces</h3><span aria-hidden="true">↗</span></a></section>'''
page('/','Software engineer', 'Personal AI, full-stack products, and shipped client work. Explore Mobolaji Ogunbiyi’s projects and interactive demos.',home)

page('/projects/','Selected work','Explore Kora, KS App, delivered client systems, and ongoing engineering work.',f'''<section class="index-hero shell"><p class="hello">Selected work</p><h1>Built to be used.<br><span>Made to be explored.</span></h1><p>Personal tools, business software, and the engineering that connects them.</p></section><section class="shell catalog-kora">{kora_feature()}</section><section class="shell">{work_pair()}</section><section class="shell exploration"><div><p class="hello">On the workbench</p><h2>WorldBuilder</h2><p>Exploring durable state and structured generation for imagined worlds. An ongoing engineering project.</p></div>{link('Explore the project','/projects/worldbuilder/')}</section>''')

kora=hero('Kora','A personal AI assistant with a place for your context, tools, and work.','<span>December 2025 — Present</span><span>Personal project · Public source</span><span>React / Tauri / TypeScript / SQLite</span>',link('Explore the demo','#demo',True)+link('View source',GH))
kora+=f'''<section class="shell demo-section" id="demo"><div class="demo-heading"><div><h2>Meet your other workspace.</h2><p>Explore a fictional day in Kora. Browse work, open a conversation, and follow the context.</p></div><span class="demo-disclosure">Interactive sample · No live AI</span></div><div class="demo-embed" data-embed="/demos/kora/#/kora"><div class="demo-cover">{image('/assets/projects/kora-interactive-sample.png','Preview of the interactive Kora sample',eager=True)}<div class="demo-cover-action"><button class="action action--primary" data-load-demo>Open interactive demo <span aria-hidden="true">↗</span></button><p>Uses fictional data. No account needed.</p></div></div></div><div class="demo-caption"><p>The demo adapts Kora’s real UI components for the browser. Actions change sample data only.</p><a href="/demos/kora/" target="_blank" rel="noopener">Open in a full window ↗</a></div></section>'''
kora+=section('A personal assistant needs more than a chat box.','<p class="lead">The useful part is continuity: knowing what you are working on, finding the relevant context, and keeping the result somewhere you can use it again.</p><p>Kora brings conversations, personal knowledge, and structured work into a Windows application. A shared runtime connects the desktop interface, CLI, and Chrome extension, with durable state in SQLite.</p>')
kora+=section('What I built.','''<div class="decision-list"><article><h3>One runtime, several ways in.</h3><p>I extended Pi’s open-source foundation with Kora’s tools, skills, personal context, and product services. The interfaces share behavior rather than each implementing a separate assistant.</p></article><article><h3>Context with somewhere to live.</h3><p>Persistent records and hybrid retrieval connect the assistant to personal knowledge and work. Keeping state locally makes it inspectable; model requests still use the configured provider.</p></article><article><h3>Work that can continue.</h3><p>Durable sessions and stored artifacts give the assistant a way to pick up existing work instead of starting every interaction from scratch.</p></article></div>''')
kora+=section('Follow the architecture.',f'''<div class="flow-diagram"><div><b>Desktop · CLI · Browser</b><p>Interfaces for the same assistant</p></div><span aria-hidden="true">↓</span><div><b>Kora runtime</b><p>Pi foundation · tools & skills · context · sessions</p></div><span aria-hidden="true">↓</span><div><b>Persistent state & connected tools</b><p>SQLite · personal knowledge · files · permitted actions</p></div></div><p><a class="text-link" href="/work-writing/kora-runtime/">Read the engineering walkthrough ↗</a></p>''')
kora+=section('Test the messy parts.','''<p class="lead">What happens when a plan changes halfway through the week?</p><p>I built an evaluation harness with simulated-user interactions, controlled event timing, changing workweek scenarios, and blinded review. It examines task completion, memory persistence, authorization boundaries, and recovery across restarts.</p><div class="scenario"><h3>A changing week</h3><ol><li>A person gives the assistant plans and constraints.</li><li>New information changes what is feasible.</li><li>A later interaction tests whether the assistant kept the right context.</li><li>The review inspects the actual outcome, including missed work and recovery.</li></ol></div><p>This is ongoing evaluation work. The interactive sample above demonstrates the interface; it does not run this evaluation or make a live agent request.</p>''')
kora+=section('Built in the open.',f'<p>Kora is in active development. The public repository contains the Windows app, runtime, and setup instructions, including its Pi-derived foundation and license notices.</p>{link("Explore the repository",GH,True)}')
page('/projects/kora/','Kora — Personal AI','Explore Kora’s interactive sample and the engineering behind a local-first Windows AI assistant.',kora)

ks=hero('KS App','People and an AI operator, working on the same business records.','<span>May 2026 — Present</span><span>Private project · In development</span><span>Next.js / TypeScript / PostgreSQL / Supabase</span>',link('Explore a workflow','#workspace',True))
ks+='''<section class="shell demo-section" id="workspace"><div class="demo-heading"><div><h2>From client context to the next action.</h2><p>Select a project, inspect its context, and prepare a sample update.</p></div><span class="demo-disclosure">Interactive illustration · Fictional records</span></div><div class="ks-sample" data-ks-sample><div class="ks-sample-sidebar"><strong>Northstar Studio</strong><p>Project workspace</p><label for="project-search">Find a project</label><input id="project-search" type="search" placeholder="Search sample projects"><div class="sample-project-list"><button class="sample-project active" data-project="website" aria-pressed="true">Website refresh<span>Juniper Wellness</span></button><button class="sample-project" data-project="brand" aria-pressed="false">Brand guidelines<span>Cedar & Co.</span></button><button class="sample-project" data-project="onboarding" aria-pressed="false">Client onboarding<span>Northstar Studio</span></button></div><p class="no-projects" hidden>No matching projects.</p></div><div class="ks-sample-content"><div class="sample-title"><span class="status" data-project-status>In progress</span><button class="text-button" data-reset-sample>Reset sample ↺</button></div><h3 data-project-title>Website refresh</h3><p data-project-client>Juniper Wellness · Client delivery</p><div class="sample-tabs" role="group" aria-label="Project view"><button aria-pressed="true" data-sample-tab="overview">Overview</button><button aria-pressed="false" data-sample-tab="activity">Activity</button></div><div data-sample-overview><h4>The next milestone</h4><p data-project-detail>Review the homepage direction with the client, then prepare the remaining service pages.</p><div class="sample-task"><input id="sample-task" type="checkbox"><label for="sample-task">Review the latest project notes</label></div><button class="action action--primary" data-prepare-update>Prepare sample update <span aria-hidden="true">↗</span></button></div><div data-sample-activity hidden><p data-activity-empty>No changes in this sample yet.</p><ul data-activity-list></ul></div><div class="sample-draft" hidden aria-live="polite"><h4>Draft client update</h4><p data-draft-text></p><span>Prepared locally from fictional records. Nothing has been sent.</span></div></div></div><p class="media-caption">This portfolio illustration explains the workflow using local sample data. It is not the live KS App interface or an executing AI agent.</p></section>'''
ks+=section('A connected business workspace.','<p class="lead">Client information should travel with the work.</p><p>KS App brings CRM, project delivery, finance, knowledge, and client portals into one workspace. Its AI operator uses the same domain services as the human interface, so a request is grounded in the application’s records and permissions.</p>')
ks+=section('The engineering underneath.','''<div class="decision-list"><article><h3>Permissions belong to the application.</h3><p>Workspace identity and allowed operations come from server-owned context. The model does not get to choose its tenant, role, or credentials.</p></article><article><h3>Skills guide. Tools act.</h3><p>Versioned skill guidance and on-demand tool discovery expose the operations needed for the work. Tools call shared business services instead of inventing a second data layer.</p></article><article><h3>Keep the record of what happened.</h3><p>Persistent conversations, durable workflows, approvals, and action receipts support recovery after interruptions. Uncertain external actions need reconciliation before another attempt.</p></article></div>''')
ks+=section('One action, one set of rules.','''<div class="flow-diagram"><div><b>Person or AI operator</b><p>Request a business operation</p></div><span aria-hidden="true">↓</span><div><b>Shared domain services</b><p>Workspace identity · permissions · approvals</p></div><span aria-hidden="true">↓</span><div><b>Records & action history</b><p>PostgreSQL / Supabase · persisted outcomes · recovery</p></div></div>''')
ks+=section('Where it stands.','<p>KS App is an active private development project. The source implements the workspace and operator architecture; complete release qualification and production readiness remain ongoing. The sample is designed to make its product model understandable without exposing a client workspace.</p><p><a class="text-link" href="/commercial-work/">See my shipped client work ↗</a></p>')
page('/projects/ks-app/','KS App — Business workspace','A multi-tenant business platform with shared services for people and an AI operator. Explore an illustrated workflow.',ks)

clients=[('zubes-grub.webp',"Zube’s Grub",'Food & hospitality','A Nigerian-American food brand, with a clear route from exploring the menu to ordering.','Website and customer journey; the accompanying engineering walkthrough covers commerce ownership, kitchen state, and recovery.','https://zubesgrub.com/'),('aboh-consulting.webp','Aboh Consulting','Consulting','Make complex consulting and Salesforce services easy to understand.','Structured service presentation and a clear inquiry path for prospective clients.','https://abohconsulting.com'),('divine-care.webp','Divine Care Services','Healthcare','Help patients find services, provider information, and the booking path.','Patient-facing website structure, service presentation, and responsive implementation.','https://www.mydivinecareservices.com/'),('fitfusion-wellness.webp','FitFusion Wellness Center','Wellness','Connect the practice’s approach to services and consultation information.','Website design and implementation, with an accessible service and consultation journey.','https://fitfusionwellnesscenter.com/')]
commercial=hero('Built for business.','Client websites and systems delivered through Kora Studio.','<span>Founder & Software Engineer</span><span>May 2026 — Present</span>',link('Visit Kora Studio','https://builtbykora.com'))
commercial+='<section class="shell client-list">'
for src,name,category,need,role,url in clients:
    commercial+=f'<article class="client-case"><a class="client-case-image" href="{url}">{image("/assets/commercial/"+src,name+" website")}</a><div><p class="hello">{category}</p><h2>{name}</h2><p class="lead">{need}</p><p>{role}</p><div class="action-row">{link("Visit live site",url)}'+(link('Engineering walkthrough','/work-writing/zubes-grub-system/') if 'zubes' in src else '')+'</div></div></article>'
commercial+='</section>'+section('From idea to delivery.','<p>I founded Kora Studio and delivered eight client websites and operational systems. The work has involved interfaces, data models, CRM, booking, payments, integrations, and deployment—with the scope shaped by each business.</p><p>Running the studio also means translating requests, choosing practical tradeoffs, and taking responsibility for delivery.</p>')
page('/commercial-work/','Client work','Selected websites and business systems delivered by Mobolaji Ogunbiyi through Kora Studio.',commercial)

world=hero('WorldBuilder','Exploring the engineering of worlds that can grow without losing their history.','<span>Ongoing project</span><span>Domain modeling / TypeScript / PostgreSQL</span>')
world+='''<section class="shell world-intro"><p class="world-question">A world changes.<br><span>What should stay true?</span></p><p>WorldBuilder investigates that question through structured generation, immutable content, and durable state.</p></section>'''
world+=section('The idea.','<p class="lead">A generated world should have more than a collection of disconnected answers.</p><p>I’m exploring how creative direction can become structured world data with clear identities, traceable revisions, and a workflow that can continue over time.</p>')
world+=section('The current implementation.','<div class="decision-list"><article><h3>Seed-to-Frame domain</h3><p>A pure domain layer defines the initial structured world model and its rules.</p></article><article><h3>Durable content</h3><p>Immutable bodies and PostgreSQL-backed state separate large content from the records that coordinate work.</p></article><article><h3>Provider composition</h3><p>Codex SDK composition and an authentication verifier prepare the integration boundary. Current runtime exercises are scripted.</p></article></div>')
world+=section('What is still being built.','<p>The current version does not yet provide a complete generation workflow, live model dispatch, or downstream world products. I’m keeping the project here as a record of engineering exploration, with the implementation distinguished from the intended experience.</p><p><a class="text-link" href="/projects/kora/">Explore Kora, my featured AI project ↗</a></p>')
page('/projects/worldbuilder/','WorldBuilder — Work in progress','An ongoing exploration of structured world generation, immutable content, and durable state.',world)

about='''<section class="about-opening shell"><div><p class="hello">A little about me</p><h1>Curious about people.<br><span>Serious about building.</span></h1></div><div class="about-intro"><p>I’m Mobolaji, a software engineer in Maryland and the founder of Kora Studio.</p><p>I study Computer Science and Psychology. I’m interested in both sides of software: the systems that make it work and the people who need it to make sense.</p><p>My work moves between full-stack products, personal AI, and practical problems for businesses. I enjoy taking an idea all the way through the interface, data, and details.</p></div></section>'''
about+=section('A few places I’ve built.','''<div class="experience-list"><article><span>2026 — Present</span><div><h3>Kora Studio</h3><p>Founder & Software Engineer</p><p>Client websites and operational systems across healthcare, food service, wellness, and consulting.</p></div></article><article><span>Summer 2025</span><div><h3>M&T Bank</h3><p>Technology Intern</p><p>Co-developed an NLP application that maps document descriptions to ranked retention-code recommendations, and presented it to internal stakeholders.</p></div></article><article><span>2025</span><div><h3>JUNEBRAIN</h3><p>Software Engineering Intern</p><p>Computer-vision work for an ophthalmic imaging prototype: pupil localization, gaze estimation, and image-quality checks.</p></div></article><article><span>Summer 2024</span><div><h3>POETS research</h3><p>Machine Learning Research Intern</p><p>Built a regression pipeline using optimization data to predict boost-converter power density, and a command-line tool for comparing candidate switches.</p></div></article><article><span>2024 — Present</span><div><h3>DAMS Lab</h3><p>Undergraduate Researcher</p><p>Python and local-LLM workflows for detecting and analyzing changes in smart-IoT privacy policies.</p></div></article></div>''')
about+=section('Technology that meets people where they are.','''<p class="hello">Seneca Signal · First place, PowerUpTech 2025</p><p class="lead">Neighborhood information should be reachable even when Wi-Fi isn’t.</p><p>Our team designed Seneca Signal for Buffalo’s Seneca-Babcock neighborhood: an admin dashboard, mobile-friendly website, and SMS interface connecting community information.</p><p>I led UI/UX and architecture, helped plan the product, and presented the winning demo. We later demonstrated the solution at the Microsoft-sponsored TechConnect 2025 AI for Social Good conference.</p><p>The most interesting constraint was accessibility in the everyday sense: making useful information reachable through the devices and connections people already had.</p>''','seneca')
about+=section('What’s next.',f'<p class="lead">I’m looking for software engineering and applied AI roles after graduating in May 2027.</p><p>I’m drawn to teams where engineers understand the product, make thoughtful technical decisions, and care about what happens after shipping.</p><div class="action-row">{link("Get in touch",EMAIL,True)}{link("Read my resume","/assets/resume.pdf")}</div>')
page('/about/','About','Meet Mobolaji Ogunbiyi: software engineer, Kora Studio founder, and Computer Science and Psychology student.',about)

articles=[('zubes-grub-system',"Designing Zube’s Grub",'Client engineering','How customer ordering, payment confirmation, kitchen operations, and recovery fit together.'),('kora-runtime','One runtime, three surfaces','Agent architecture','Why the desktop, browser, and CLI share the same assistant runtime.'),('websites-as-systems','Websites as complete systems','Product engineering','Following a customer’s action into the business workflow behind it.'),('building-with-ai','Building with AI, owning the decisions','Engineering practice','How I use agents while keeping scope, review, and engineering judgment in my hands.')]
writing='<section class="index-hero shell"><p class="hello">Notes from the work</p><h1>How it works.<br><span>Why I built it that way.</span></h1><p>Engineering decisions, explained through the projects they shaped.</p></section><section class="shell writing-index">'
for slug,title,tag,desc in articles:
    writing+=f'<a class="writing-entry" href="/work-writing/{slug}/"><span>{tag}</span><div><h2>{title}</h2><p>{desc}</p></div><span aria-hidden="true">↗</span></a>'
writing+='</section>'
page('/work-writing/','Writing','Engineering notes on personal AI, client systems, and building software with care.',writing)
print('Built 8 portfolio pages.')
