import {getWorkCalendarSnapshot} from './work-calendar-fixture';
import type {MemoryRecord, BrainPage, PersonRecord, ProfileRecord, KnowledgeSource, OutputSummary, WellbeingRecord, FinanceAccount, FinanceTransaction, FinanceBill, FinanceSubscription, FinanceGoal, FinanceBudget, LifeTodayFeed, LifeOverview} from './upstream/lib/runtime';
// All data below is fictional. Mutations live only in this browser tab.
const now='2026-09-13T14:00:00Z', day='2026-09-13', zone='America/New_York';
const base={provenance:'Fictional sample · saved by Alex',version:1,createdAt:now,updatedAt:now};
const stamp=()=>new Date().toISOString();
const copy=<T>(v:T):T=>structuredClone(v);
const missing=()=>{throw new Error('This sample record is no longer available. Reset the demo to restore its fictional data.');};
const external=async()=>{throw new Error('This browser sample cannot access files, connect providers, or run AI. Explore the fictional records already included.');};
const find=(xs:any[],id:string)=>xs.find(x=>(x.id??x.key)===id)??missing();
const matches=(x:unknown,q?:string)=>!q||JSON.stringify(x).toLowerCase().includes(q.toLowerCase());
const page=(xs:any[],input:any={})=>{const filtered=xs.filter(x=>matches(x,input.query)&&(!input.state||x.state===input.state)&&(!input.status||x.status===input.status)&&(!input.kind||x.kind===input.kind)&&(!input.category||x.category===input.category)&&(!input.states?.length||input.states.includes(x.state)));return copy({items:filtered,complete:true,matchingCount:filtered.length});};
const settled=(record:any)=>copy({status:'settled' as const,record,replayed:false});
const change=(xs:any[],id:string,input:any)=>{const x=find(xs,id);if(input.expectedVersion!==undefined&&x.version!==input.expectedVersion)return {status:'conflict' as const,current:copy(x),replayed:false};const {expectedVersion,expectedUpdatedAt,requestKey,...fields}=input;Object.assign(x,fields,{version:(x.version??0)+1,updatedAt:stamp()});return settled(x);};
const changedRecord=(xs:any[],id:string,input:any)=>{const r=change(xs,id,input);if(r.status==='conflict')throw new Error('Sample record changed; reopen it and try again.');return r.record;};
const create=(xs:any[],input:any)=>{const x={...base,id:crypto.randomUUID(),state:'active',...input};delete x.requestKey;xs.unshift(x);return settled(x);};
const memories:MemoryRecord[]=[['travel','Alex prefers walkable neighborhoods and quiet places to stay.'],['food','Alex enjoys vegetarian food and likes finding independent cafés.'],['work','Alex is preparing a design portfolio and prefers specific feedback over general praise.'],['writing','Use a warm, concise tone when helping Alex draft messages.']].map(([id,content])=>({...base,id,content,status:'active',confidence:1}));
const pages:BrainPage[]=[{...base,id:'lisbon-notes',title:'Lisbon · places and possibilities',kind:'note',state:'active',bodyMarkdown:'# A week in Lisbon\n\nStay somewhere walkable, with a café nearby and easy access to the river.\n\n## Shortlist\n- Príncipe Real: gardens and quiet streets.\n- Estrela: neighborhood cafés and tram connections.\n\n## First afternoon\nDrop off bags, take a short walk, and leave the evening open.'},{...base,id:'portfolio-notes',title:'Portfolio direction',kind:'reference',state:'active',bodyMarkdown:'# Show the work first\n\nThree case studies, each with a clear problem, my contribution, and a useful result.\n\n- Keep the introduction short.\n- Show real screens.\n- Make the mobile view easy to scan.'},{...base,id:'dinner-notes',title:'A simple neighborhood dinner',kind:'note',state:'active',bodyMarkdown:'# Saturday dinner\n\nA relaxed evening for eight. Ask about dietary preferences before choosing the menu.\n\n## Ideas\nRoasted vegetables, bread, a big salad, and something easy for dessert.'}];
const people:PersonRecord[]=[{...base,id:'maya',displayName:'Maya Chen',relationshipLabel:'Friend · travel companion',contextMarkdown:'Planning the Lisbon trip together. Enjoys bookstores and unhurried mornings.',providerRefs:[],state:'active'},{...base,id:'jordan',displayName:'Jordan Rivera',relationshipLabel:'Design collaborator',contextMarkdown:'Reviewing Alex’s portfolio case studies. Helpful with typography and mobile layouts.',providerRefs:[],state:'active'},{...base,id:'sam',displayName:'Sam Patel',relationshipLabel:'Neighbor',contextMarkdown:'Interested in the neighborhood dinner. Likes cooking and knows the local farmers market.',providerRefs:[],state:'active'}];
const profiles:ProfileRecord[]=[['name','Alex Morgan','identity'],['location','Brooklyn, New York','identity'],['communication_style','Warm, concise, and specific','communication'],['travel_preferences','Walkable neighborhoods, independent cafés, and room to wander','preferences'],['timezone',zone,'preferences']].map(([key,value,category])=>({...base,key,value,category:category as any,state:'confirmed',mutability:'editable',source:{kind:'owner_entered',label:'Saved by you',correctionOwner:'owner'}}));
const sources:KnowledgeSource[]=[{...base,id:'travel-guide',label:'Lisbon neighborhood notes',sourceKind:'inline',format:'inline',mediaType:'text/plain',extraction:{parser:'sample-text',coverage:{status:'complete',indexed:['text'],omitted:[]}},retrievalRole:'task_relevant',temporalScope:'current',freshness:'persisted',contentHash:'fictional-source',state:'active'}];
const outputs:OutputSummary[]=[{id:'lisbon-brief',title:'Lisbon first-day plan.md',mediaType:'text/markdown',byteSize:240,sha256:'fictional-preview',role:'output',createdAt:now,updatedAt:now,previewState:'available'}];
const content='# Lisbon · first afternoon\n\nDrop off bags, find a nearby café, and walk toward the river. Keep dinner flexible.\n\n## Remember\nComfortable shoes, a charged phone, and space to get pleasantly lost.\n\nFictional portfolio sample.';
const histories=new Map<string,any[]>();
const wb:WellbeingRecord[]=[{...base,id:'breakfast',kind:'meal',title:'Breakfast at home',payload:{description:'Oats with berries and yogurt',mealType:'breakfast',foods:['Oats','Berries','Yogurt']},recordedAt:'2026-09-13T12:00:00Z',privacy:'private',source:{kind:'manual',label:'Saved by Alex'},state:'active'},{...base,id:'water',kind:'drink',title:'A glass of water',payload:{name:'Water',volumeMl:300},recordedAt:now,privacy:'private',source:{kind:'manual',label:'Saved by Alex'},state:'active'},{...base,id:'walk',kind:'routine',title:'A little time outside',payload:{name:'Afternoon walk',cadence:'daily',enabled:true,preferredWindow:'afternoon',cue:'After lunch',reason:'A change of scene',daysOfWeek:[0,1,2,3,4,5,6],completionChoices:['done','skipped']},recordedAt:now,privacy:'private',source:{kind:'manual',label:'Saved by Alex'},state:'active'},{...base,id:'energy',kind:'observation',title:'Morning energy',payload:{category:'energy',value:'Rested',rating:4,notes:'A quiet start and a good breakfast.'},recordedAt:now,privacy:'private',source:{kind:'manual',label:'Saved by Alex'},state:'active'},{...base,id:'reflection',kind:'note',title:'Room to slow down',payload:{body:'An unhurried morning helped. Leave a little space between plans this week.'},recordedAt:now,privacy:'private',source:{kind:'manual',label:'Saved by Alex'},state:'active'}];
for(let n=0;n<7;n++)wb.push({...base,id:'sleep-'+n,kind:'measurement',title:'Sleep duration',payload:{metric:'Sleep duration',value:[7.5,7,8,7.25,7.75,8,7.5][n],unit:'hours'},recordedAt:`2026-09-${String(7+n).padStart(2,'0')}T11:00:00Z`,privacy:'private',source:{kind:'manual',label:'Saved by Alex'},state:'active'});
const moneySources={plaid:{state:'ok' as const},gmail:{state:'ok' as const},accounts:{state:'ok' as const},transactions:{state:'ok' as const},plans:{state:'ok' as const},receipts:{state:'ok' as const}};
const accounts:FinanceAccount[]=[{accountId:'checking',connectionId:'sample-manual',name:'Everyday account',type:'depository',currency:'USD',balanceMinor:326500,updatedAt:now,connectionState:'manual',balanceQualification:'manual',includedInAllowance:true},{accountId:'savings',connectionId:'sample-manual',name:'Travel savings',type:'depository',currency:'USD',balanceMinor:185000,updatedAt:now,connectionState:'manual',balanceQualification:'manual',includedInAllowance:false}];
const transactions:FinanceTransaction[]=[['groceries','Green Market',4850,'Food'],['coffee','Corner café',-650,'Food'],['books','Neighborhood Books',2400,'Personal'],['income','Design project',-220000,'Income']].map(([id,merchant,amount,category])=>({id:String(id),connectionId:'sample-manual',providerTransactionId:String(id),accountId:'checking',accountName:'Everyday account',accountType:'depository',amountMinor:Number(amount),currency:'USD',merchant:String(merchant),category:String(category),occurredAt:now,pending:false,updatedAt:now,annotationVersion:1,evidenceState:'none',freshness:'manual'}));
const bills:FinanceBill[]=[{id:'internet',billerName:'Home internet',expectedAmountMinor:6500,currency:'USD',accountId:'checking',accountName:'Everyday account',dueRule:'Monthly on the 18th',nextExpectedAt:'2026-09-18T12:00:00Z',autopayState:'enabled',reconciliationEvidence:[],state:'active',updatedAt:now}];
const subscriptions:FinanceSubscription[]=[{id:'music',merchantName:'Music subscription',accountId:'checking',accountName:'Everyday account',currency:'USD',cadence:'monthly',expectedAmountMinor:1099,nextExpectedAt:'2026-09-20T12:00:00Z',reconciliationEvidence:[],state:'active',updatedAt:now}];
const financeGoals:FinanceGoal[]=[{id:'travel-fund',displayName:'Lisbon travel fund',goalKind:'savings',targetAmountMinor:240000,currentAmountMinor:185000,currency:'USD',linkedAccountIds:['savings'],state:'active',updatedAt:now}];
const budgets:FinanceBudget[]=[{id:'food-budget',displayName:'Groceries and cafés',periodKind:'monthly',category:'Food',targetAmountMinor:45000,currency:'USD',state:'active',updatedAt:now}];
let allowanceSettings={includedAccountIds:['checking'],dailyFloorMinor:2500,bufferMinor:100000,obligationHorizonDays:30,updatedAt:now,version:1,sources:moneySources};
const financeList=(key:string,xs:any[],state:any='active')=>copy({[key]:xs.filter(x=>!state||x.state===state),archivedCount:xs.filter(x=>x.state==='archived').length,complete:true,total:xs.length,viewerTimeZone:zone,sources:moneySources});
const wbSources=()=>({state:'local_only',local:{state:'current',visibleRecordCount:wb.length,lastRecordedAt:now,dataKinds:[...new Set(wb.map(x=>x.kind))]},external:[],complete:true,restrictedOmitted:false});
const store:any={memory:memories,page:pages,person:people,profile:profiles,'knowledge-source':sources};
export const brainLifeRuntime={
 memoriesPage:async(i:any={})=>page(memories,i),memoryPage:async(i:any={})=>page(memories,i),pagesPage:async(i:any={})=>page(pages,i),peoplePage:async(i:any={})=>page(people,i),profilePage:async(i:any={})=>page(profiles,i),knowledgeSourcesPage:async(i:any={})=>page(sources,i),outputsPage:async(i:any={})=>page(outputs,i),
 brainRecord:async(surface:string,id:string)=>copy({surface,record:find(store[surface]??[],id)}),
 createMemory:async(i:any)=>{const r=create(memories,{content:i.content,status:'active',confidence:1});return r;},correctMemory:async(id:string,i:any)=>{const x=find(memories,id);const old=x.content;const r=change(memories,id,i);histories.set(id,[...(histories.get(id)??[]),{action:'corrected',content:i.content,previousContent:old,occurredAt:stamp()}]);return r;},memoryHistory:async(id:string)=>({revisions:copy(histories.get(id)??[{action:'remembered',content:find(memories,id).content,occurredAt:now}])}),
 memoryPipelineHealth:async()=>({automaticLearning:{enabled:false,updatedAt:now},processing:{state:'idle',pending:0,processing:0,failed:0},recent:[],deletionReceipts:[],processingBoundary:{extraction:'remote_model',embedding:'local_runtime',canonicalStorage:'local_sqlite'},complete:true}),updateMemorySettings:external,
 createPage:async(i:any)=>create(pages,i),updatePage:async(id:string,i:any)=>change(pages,id,i),archivePage:async(id:string,i:any)=>change(pages,id,{...i,state:'archived'}),createPerson:async(i:any)=>create(people,{providerRefs:[],...i}),updatePerson:async(id:string,i:any)=>change(people,id,i),personWorkspace:async(id:string)=>copy({person:find(people,id),work:{items:[],complete:true}}),
 setProfileRecord:async(key:string,i:any)=>{if(!profiles.some(x=>x.key===key))profiles.push({...base,key,value:i.value,state:'confirmed',category:'preferences',mutability:'editable'});return change(profiles,key,i);},setProfileFact:async(i:any)=>brainLifeRuntime.setProfileRecord(i.key,i),transitionProfileRecord:async(key:string,i:any)=>change(profiles,key,{expectedVersion:i.expectedVersion,state:({confirm:'confirmed',dismiss:'dismissed',archive:'archived',restore:'confirmed'} as any)[i.action]}),
 profileHistoryPage:async(i:any={})=>page(profiles.filter(x=>!i.profileKey||x.key===i.profileKey).map(x=>({profileKey:x.key,version:x.version,action:'created',provenance:x.provenance,state:x.state,recordedAt:x.updatedAt}))),
 profileOverview:async()=>({portrait:{sections:['identity','communication','household','preferences','privacy'].map(category=>({category,statements:profiles.filter(p=>p.category===category&&p.state==='confirmed').map(p=>({text:String(p.value),state:p.state,mutability:p.mutability,support:{key:p.key,version:p.version},source:p.source}))}))},review:{items:[],total:0,complete:true},recentChanges:{items:[],total:0,complete:true},counts:{visible:profiles.length,active:profiles.filter(p=>p.state==='confirmed').length,setupArtifacts:0,byState:Object.fromEntries(['confirmed','proposed','conflicted','archived','dismissed'].map(k=>[k,profiles.filter(p=>p.state===k).length])),byCategory:Object.fromEntries(['identity','communication','household','preferences','privacy','unknown'].map(k=>[k,profiles.filter(p=>p.category===k).length]))},complete:true,generatedAt:now}),
 knowledgeSourceWorkspace:async(id:string)=>copy({source:find(sources,id)}),knowledgeSourceSpans:async(id:string)=>({items:[{sourceId:id,label:find(sources,id).label,version:1,start:0,end:130,text:'Príncipe Real offers gardens and independent shops. Estrela has quieter streets and neighborhood cafés. Both suit an unhurried visit.',updatedAt:now}],complete:true}),registerKnowledgeSource:async(i:any)=>{if(i.sourceKind==='file')return external();const r=create(sources,{label:i.label,sourceKind:'inline',format:'inline',mediaType:'text/plain',extraction:{parser:'sample-text',coverage:{status:'complete',indexed:['text'],omitted:[]}},retrievalRole:i.retrievalRole??'task_relevant',temporalScope:i.temporalScope??'current',freshness:'persisted',contentHash:'fictional-source'});histories.set(r.record.id,[{text:i.content??i.text??''}]);return r;},reconcileKnowledgeSource:external,updateKnowledgeSource:async(id:string,i:any)=>change(sources,id,i),unregisterKnowledgeSource:async(id:string)=>{const x=find(sources,id);sources.splice(sources.indexOf(x),1);return {status:'settled',id,replayed:false};},
 deleteBrainRecord:async(surface:string,id:string)=>{const xs=store[surface]??[];const x=find(xs,id);xs.splice(xs.indexOf(x),1);return {status:'settled',id,surface,negativeRead:true,replayed:false};},
 outputWorkspace:async(id:string)=>({output:copy(find(outputs,id)),previews:[],origins:[]}),outputContent:async(id:string)=>{const x=find(outputs,id),blob=new Blob([content],{type:x.mediaType});return {blob,mediaType:x.mediaType,title:x.title,byteSize:blob.size,sha256:x.sha256};},renameOutput:async(id:string,i:any)=>change(outputs,id,i),renderOutputPreview:async()=>({status:'unsupported',previews:[],message:'Open the included Markdown output to read its contents.',replayed:false}),deleteOutput:async(id:string)=>{const x=find(outputs,id);outputs.splice(outputs.indexOf(x),1);return {status:'settled',id,negativeRead:true,replayed:false};},attachImageOutput:external,
 personalBrainSearch:async(query:string)=>brainLifeRuntime.personalBrainSearchPage({query}),personalBrainSearchPage:async(i:any)=>{const rows=[...memories.map(x=>({scope:'memory',id:x.id,title:x.content,preview:x.content,kind:'memory',route:'/brain/memory'})),...pages.map(x=>({scope:'pages',id:x.id,title:x.title,preview:x.bodyMarkdown,kind:'page',route:'/brain/pages'})),...people.map(x=>({scope:'people',id:x.id,title:x.displayName,preview:x.contextMarkdown,kind:'person',route:'/brain/people'})),...profiles.map(x=>({scope:'profile',id:x.key,title:x.key,preview:String(x.value),kind:'profile',route:'/brain/profile'})),...sources.map(x=>({scope:'knowledge_sources',id:x.id,title:x.label,preview:'Saved reference for the Lisbon trip',kind:'knowledge_source',route:'/brain/sources'})),...outputs.map(x=>({scope:'outputs',id:x.id,title:x.title??'Saved output',preview:content,kind:'output',route:'/brain/outputs'}))].filter(x=>matches(x,i.query)&&(!i.scopes?.length||i.scopes.includes(x.scope)));return {state:'ok',results:rows.map(x=>({scope:x.scope,display:{objectKind:x.kind,title:x.title},preview:x.preview,provenance:base.provenance,updatedAt:now,matchChannels:['lexical'],destination:{kind:x.kind,path:x.route+'/'+x.id},context:{state:'ready',authorization:'allowed',selectionId:x.id,evidenceHandle:x.id,display:{objectKind:x.kind,title:x.title},expiresAt:'2099-01-01T00:00:00Z'}})),complete:true,unavailableScopes:[],limitedScopes:[],coverage:[],snapshotOmissions:{changed:0,gone:0,unavailable:0}};},
 wellbeingRecords:async(i:any={})=>({...page(wb.filter(x=>(!i.kinds?.length||i.kinds.includes(x.kind))&&(!i.start||x.recordedAt>=i.start)&&(!i.end||x.recordedAt<=i.end)),i),restrictedOmitted:false,visibleTotal:wb.length}),wellbeingSources:async()=>wbSources(),wellbeingRecord:async(id:string)=>{const record=copy(find(wb,id));return {record,history:copy(histories.get(id)??[{version:record.version,action:'created',recordedAt:record.createdAt,record}])};},createWellbeingRecord:async(i:any)=>{const r=create(wb,i);return {record:r.record,replayed:false};},updateWellbeingRecord:async(id:string,v:number,i:any)=>{const r=change(wb,id,{...i,expectedVersion:v});if(r.status==='conflict')throw new Error('This sample record changed. Reopen it before saving.');return {record:r.record,replayed:false};},archiveWellbeingRecord:async(id:string,v:number)=>brainLifeRuntime.updateWellbeingRecord(id,v,{state:'archived'}),restoreWellbeingRecord:async(id:string,v:number)=>brainLifeRuntime.updateWellbeingRecord(id,v,{state:'active'}),deleteWellbeingRecord:async(id:string)=>{const x=find(wb,id);wb.splice(wb.indexOf(x),1);return {status:'settled',id,surface:'wellbeing_record',negativeRead:true,replayed:false};},
 wellbeingPrivacy:async()=>({policy:{state:'read_only',defaultPrivacy:'private',storageAuthority:'local_sqlite',writableControls:false},ordinaryUse:{permittedPrivateRecords:'wellbeing_workspace',conversationUse:'shared_personal_information_policy',restrictedRecords:'omitted',restrictedCounts:'omitted'},exactRestrictedAccess:{enforcement:'record_version_purpose_request_expiry',permittedPurpose:'kora_context_attachment',visualRead:'unavailable',wellbeingControl:'unavailable'},controls:{recordCorrection:'records',archiveRestore:'records',exactDeletion:'records',policyEditing:'unavailable',privacyHistory:'unavailable'}}),
 wellbeingTrendMetrics:async()=>({metrics:[{key:'sleep-hours',metric:'Sleep duration',unit:'hours',visibleRecordCount:7,firstRecordedAt:'2026-09-07T11:00:00Z',lastRecordedAt:now,sources:[{kind:'manual',label:'Saved by Alex'}]}],restrictedOmitted:false,excludedRecordCount:0,complete:true}),wellbeingTrendEvidence:async(i:any)=>({evidenceHandle:i.evidenceHandle,recordIds:wb.filter(x=>x.id===i.evidenceHandle).map(x=>x.id),totalExactRecords:1,complete:true}),wellbeingTrend:async(i:any)=>{const records=wb.filter(x=>x.kind==='measurement');const range={key:i.range,start:'2026-09-07T00:00:00Z',end:now,startDate:'2026-09-07',endDate:day};return {status:'insufficient',generatedAt:now,viewerTimeZone:zone,metric:{key:'sleep-hours',metric:'Sleep duration',unit:'hours',visibleRecordCount:records.length,firstRecordedAt:range.start,lastRecordedAt:now,sources:[{kind:'manual',label:'Saved by Alex'}]},range,points:records.map(x=>({id:x.id,mode:'raw',time:x.recordedAt,rangeStart:x.recordedAt,rangeEnd:x.recordedAt,value:(x.payload as any).value,metric:'Sleep duration',unit:'hours',exactRecordCount:1,recordIds:[x.id],evidenceHandle:x.id,evidenceComplete:true,aggregationMethod:'exact_value',sourceLabels:['Saved by Alex']})),totalExactRecords:records.length,excludedRecordCount:0,restrictedOmitted:false,seriesMode:'raw',seriesQualification:{state:'insufficient',exactRecordCount:records.length,recordedDayCount:7,reason:'A short fictional sample shows the recording interface.',policy:'No health interpretation is inferred from sample data.'},sourceQualification:{state:'complete',sources:wbSources()},baseline:{qualification:'unqualified',label:'Personal recorded baseline',reason:'Short fictional sample',exactRecordCount:7,recordedDayCount:7,restrictedOmitted:false,excludedRecordCount:0,complete:true,window:{start:range.start,end:now},policy:'No baseline inferred'},missingSpans:[],outageAnnotations:[],intervalCoverage:{state:'unsupported',reason:'Manual sample records',restrictedOmitted:false},observations:{state:'unsupported',items:[]},overlaps:{state:'unsupported',items:[]},overlayCatalog:{items:[],totalItems:0,complete:true,restrictedOmitted:false},selectedOverlays:{items:[],totalExactRecords:0,complete:true}};},
 financeAccounts:async(i:any={})=>copy({accounts:accounts.filter(x=>!(typeof i==='string'?i:i.id)||x.accountId===(typeof i==='string'?i:i.id)),connections:[],complete:true,total:accounts.length,viewerTimeZone:zone,sources:moneySources}),
 financeTransactions:async(i:any={})=>({...page(transactions.filter(x=>(!i.accountId||x.accountId===i.accountId)&&(!i.transactionId||x.id===i.transactionId)&&(!i.category||x.category===i.category)),i),total:transactions.length,needsReviewTotal:0,categories:['Food','Personal','Income'],sources:moneySources}),updateFinanceTransactionAnnotation:async(id:string,i:any)=>{const x=find(transactions,id);Object.assign(x,{note:i.note,category:i.category??x.category,annotationVersion:(x.annotationVersion??0)+1});return {status:'settled',annotation:{note:x.note,category:x.category??null,version:x.annotationVersion,updatedAt:stamp()},history:[{version:x.annotationVersion,note:x.note,category:x.category??null,action:'updated',recordedAt:stamp()}]};},
 financeBudgets:async(state:any='active')=>financeList('budgets',budgets,state),financeBills:async(state:any='active')=>financeList('bills',bills,state),financeBill:async(id:string)=>financeList('bills',[find(bills,id)],null),financeSubscriptions:async(state:any='active')=>financeList('subscriptions',subscriptions,state),financeSubscription:async(id:string)=>financeList('subscriptions',[find(subscriptions,id)],null),financeGoals:async(state:any='active')=>financeList('goals',financeGoals,state),financeRecurring:async(i:any={})=>copy({bills:bills.filter(x=>matches(x,i.query)),subscriptions:subscriptions.filter(x=>matches(x,i.query)),archivedCount:0,complete:true,total:bills.length+subscriptions.length,viewerTimeZone:zone,sources:moneySources}),
 updateFinanceBudget:async(id:string,i:any)=>changedRecord(budgets,id,i),createFinanceBill:async(i:any)=>create(bills,{currency:'USD',reconciliationEvidence:[],...i}).record,updateFinanceBill:async(id:string,i:any)=>changedRecord(bills,id,i),createFinanceSubscription:async(i:any)=>create(subscriptions,{currency:'USD',reconciliationEvidence:[],...i}).record,updateFinanceSubscription:async(id:string,i:any)=>changedRecord(subscriptions,id,i),createFinanceGoal:async(i:any)=>create(financeGoals,{linkedAccountIds:[],...i}).record,updateFinanceGoal:async(id:string,i:any)=>changedRecord(financeGoals,id,i),
 financeAllowanceSettings:async()=>copy(allowanceSettings),updateFinanceAllowanceSettings:async(i:any)=>{Object.assign(allowanceSettings,i,{version:allowanceSettings.version+1,updatedAt:stamp()});return copy(allowanceSettings);},financeAllowance:async()=>({generatedAt:now,viewerTimeZone:zone,currency:'USD',includedAccountIds:allowanceSettings.includedAccountIds,usedDepositoryFallback:false,availableBalanceMinor:326500,upcomingObligationsMinor:7599,incomeExpectedMinor:0,bufferMinor:allowanceSettings.bufferMinor,dailyFloorMinor:allowanceSettings.dailyFloorMinor,monthToDateOutflowMinor:7900,remainingDays:17,planningRemainderMinor:218901,dailyAllowanceMinor:12876,status:'within_plan',isNonPositive:false,explanation:'Fictional plan using a manually entered balance and saved recurring costs.',sources:moneySources}),financeReceipts:async()=>({items:[],complete:true,sources:moneySources}),resolveFinanceReceipt:external,
 financeSnapshot:async()=>copy({generatedAt:now,viewerTimeZone:zone,dailyPostedOutflows:[{date:day,currency:'USD',amountMinor:7900}],window:{days:30,cutoff:'2026-09-01T00:00:00Z',transactionLimit:250,totalTransactions:transactions.length,returnedTransactions:transactions.length,clipped:false,oldestTransactionAt:now,newestTransactionAt:now,pendingTransactions:0},connections:[],accounts,monthlyCashFlow:[{month:'2026-09',currency:'USD',inflowMinor:220000,outflowMinor:7900,netCashFlowMinor:212100,pendingInflowMinor:0,pendingOutflowMinor:0,transactionCount:transactions.length}],transactions:transactions.map(x=>({...x,pending:0})),plans:{budgets:{records:budgets},bills:{records:bills},subscriptions:{records:subscriptions},goals:{records:financeGoals},alerts:{records:[]}},sources:moneySources}),
 lifeOverview:async():Promise<LifeOverview>=>({generatedAt:now,status:'current',orientation:{currentSources:3,needsReview:0},rightNow:null,attentionCandidatesTotal:0,next:[],signals:[{domain:'money',label:'Travel fund',state:'Saved',support:'A little closer to Lisbon',destination:'/life/finances',sourceId:'money',amountMinor:185000,currency:'USD'},{domain:'wellbeing',label:'A little time outside',state:'Planned',support:'Afternoon walk, whenever it fits',destination:'/life/wellbeing',sourceId:'wellbeing'}],sources:([{id:'money',label:'Money'},{id:'wellbeing',label:'Wellbeing'},{id:'about_you',label:'About you'}] as const).map(x=>({...x,state:'current',authority:'Fictional local sample',privacyEffect:'Changes stay in this browser tab',recoveryOwner:'user'})),thread:{items:[{id:'morning',kind:'wellbeing_logged',domain:'wellbeing',occurredAt:now,title:'A quiet start',detail:'Saved breakfast and a morning reflection.',destination:'/life/wellbeing',sourceId:'wellbeing'}],complete:true},restrictedOmitted:false,day:{viewerDate:day,viewerTimeZone:zone,items:[],totalCount:0,clipped:false}}),
 lifeTodayFeed:async():Promise<LifeTodayFeed>=>{
 const snapshot=getWorkCalendarSnapshot(),generatedAt=stamp(),viewerTimeZone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 const localDay=(value:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:viewerTimeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
 const date=localDay(generatedAt), terminal=(state:string)=>['completed','cancelled','archived'].includes(state);
 const open=snapshot.tasks.filter(t=>!terminal(t.state)&&t.dueAt).map(item=>({item,timing:(localDay(item.dueAt!)<date?'overdue':localDay(item.dueAt!)===date?'today':'future') as 'overdue'|'today'|'future',due:{kind:'instant' as const,instant:item.dueAt!,viewerDate:localDay(item.dueAt!)},canonicalRoute:'/work/tasks/'+item.id}));
 const current=open.filter(t=>t.timing!=='future'),future=open.filter(t=>t.timing==='future');
 const settled=snapshot.tasks.filter(t=>['completed','cancelled'].includes(t.state)&&localDay(t.updatedAt)===date).map(item=>({item,disposition:item.state as 'completed'|'cancelled',settledAt:item.updatedAt,viewerDate:date,canonicalRoute:'/work/tasks/'+item.id}));
 const nextDay=new Date();nextDay.setHours(24,0,0,0);
 return {generatedAt,date,viewerTimeZone,viewerTimeZoneAuthority:{source:'system'},freshness:{state:'current',generatedAt,viewerDate:date,viewerTimeZone,nextDayChangeAt:nextDay.toISOString()},assistantActivity:[],calendar:snapshot.events.filter(event=>event.start.kind==='date'?event.start.date===date:localDay(event.start.instant)===date),work:{current:{items:current,totalCount:current.length,overdueCount:current.filter(t=>t.timing==='overdue').length,todayCount:current.filter(t=>t.timing==='today').length,clipped:false},future:{items:future,totalCount:future.length,clipped:false},settled:{items:settled,totalCount:settled.length,clipped:false,order:'settled_at_descending'},order:'overdue_then_due_ascending_priority_descending',viewAllRoute:'/work/tasks'},dueCommitments:current.map(t=>t.item),continuityReferences:[],pendingConfirmations:[],sources:{schedules:{state:'ok'},calendar:{state:'ok'},native_work:{state:'ok'},confirmations:{state:'ok'}}};
 },
};

const resetArrays:any[][]=[memories,pages,people,profiles,sources,outputs,wb,accounts,transactions,bills,subscriptions,financeGoals,budgets];
const initialState=copy(resetArrays);
const initialAllowance=copy(allowanceSettings);
export function resetBrainLifeFixture(){resetArrays.forEach((xs,index)=>xs.splice(0,xs.length,...copy(initialState[index])));histories.clear();allowanceSettings=copy(initialAllowance);}
