export type * from './upstream/lib/runtime';
export class RuntimeRequestError extends Error {code:string;constructor(message:string,options:{code?:string}={}){super(message);this.code=options.code??'demo_unavailable';}}
const date='2026-09-10T14:00:00Z';
const seeds=[
{id:'lisbon',title:'A week in Lisbon',area:'Travel',purposeMarkdown:'A walkable neighborhood, room for wandering, and a plan that still feels like a holiday.',currentPositionMarkdown:'Dates are set. Two neighborhoods shortlisted; accommodation is next.',lifecycle:'active',targetDate:'2026-10-12'},
{id:'portfolio',title:'Launch my design portfolio',area:'Creative',purposeMarkdown:'Turn three finished projects into a small, thoughtful home for my work.',currentPositionMarkdown:'The case studies are drafted. Reviewing the first visual direction.',lifecycle:'active',targetDate:'2026-09-30'},
{id:'dinner',title:'Host a neighborhood dinner',area:'People',purposeMarkdown:'Bring a few neighbors together over a simple meal.',currentPositionMarkdown:'A relaxed evening for eight. Pick a date before planning the menu.',lifecycle:'planned',targetDate:'2026-10-03'},
{id:'reading',title:'Make space for reading',area:'Personal',purposeMarkdown:'Keep a small reading list and enjoy a chapter without racing to finish.',currentPositionMarkdown:'Finished the first book. Saving a few notes before choosing the next.',lifecycle:'achieved'}];
export let goals:any[]=[]; export let tasks:any[]=[];
export function reset(){goals=seeds.map(x=>({...x,shape:'finish',priority:2,sensitivity:'private',provenance:'synthetic_demo',version:1,createdAt:date,updatedAt:date}));tasks=[{id:'stay',goalId:'lisbon',title:'Choose a place to stay',description:'Compare the two saved neighborhoods. Keep the nightly budget under €150.',state:'active'},{id:'flights',goalId:'lisbon',title:'Save flight details',description:'Add the confirmed flight times to the trip notes.',state:'completed'},{id:'route',goalId:'lisbon',title:'Plan a first-day walk',description:'A short route from the apartment with coffee and a river view.',state:'planned'},{id:'review',goalId:'portfolio',title:'Review the homepage direction',description:'Check the first screen on a phone and trim the introduction.',state:'active'},{id:'images',goalId:'portfolio',title:'Export project images',description:'Choose screenshots that show the finished work.',state:'planned'},{id:'date',goalId:'dinner',title:'Choose a date with the neighbors',description:'Saturday or Sunday evening; ask which is easier.',state:'planned'}];}
reset();
export const runtime={isPreview:true,goalsPage:async(input:any={})=>({items:goals.filter(g=>(input.filter==='terminal'?g.lifecycle==='achieved':input.filter==='open'?!['achieved','archived','stopped'].includes(g.lifecycle):!input.filter||g.lifecycle===input.filter)&&(!input.query||[g.title,g.area,g.purposeMarkdown].join(' ').toLowerCase().includes(input.query.toLowerCase()))).map(goal=>({goal,visibleOpenWorkItemCount:tasks.filter(t=>t.goalId===goal.id&&t.state!=='completed').length,visibleBlockedWorkItemCount:0,visibleOverdueWorkItemCount:0,inUserAttention:goal.id==='lisbon',nextOpenWorkItem:tasks.find(t=>t.goalId===goal.id&&t.state!=='completed')})),complete:true}),createGoal:async({goal}:any)=>{const g={...goal,id:crypto.randomUUID(),sensitivity:'private',version:1,createdAt:date,updatedAt:date};goals.push(g);return {goal:g,record:g,status:'settled'};},updateGoal:async(id:string,_v:number,changes:any)=>{const g=goals.find(g=>g.id===id);Object.assign(g,changes,{version:g.version+1});return {goal:g,record:g,status:'settled'};}};
