import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {HashRouter,Routes,Route,NavLink,Link,useParams,useNavigate} from 'react-router-dom';
import {QueryClient,QueryClientProvider,useQueryClient} from '@tanstack/react-query';
import {MotionConfig} from 'motion/react';
import {MessageSquare,Target,BookOpen,RotateCcw,ArrowLeft,ArrowUpRight,Check,Search,FileText,ChevronRight,Plus} from 'lucide-react';
import '@fontsource-variable/mona-sans';
import {ProjectsWorkspace} from './upstream/features/work/ProjectsWorkspace';
import {ViewBarProvider} from './upstream/app/ViewBar';
import {KoraMark} from './upstream/components/KoraMark';
import {Button,Badge,TooltipProvider,ToastProvider} from './upstream/components/primitives';
import {runtime,goals,tasks,reset} from './fixture';
import './upstream/styles/tokens.css';
import './upstream/styles/app.css';
import './demo.css';
const pages=[{id:'lisbon-notes',title:'Lisbon: where to stay',tag:'Travel',excerpt:'Two neighborhoods, one simple decision.',body:'Príncipe Real has quiet streets, gardens, and independent cafés. It is a little farther from the waterfront. Chiado is central and convenient for a first visit, with more activity in the evenings.\n\nThe plan: choose a refundable apartment in Príncipe Real. Keep the nightly budget below €150 and prioritize natural light, a kitchen, and a short walk to public transport.\n\nArrival day stays deliberately light: check in, get coffee, and walk down toward the river.',linked:'lisbon'}, {id:'portfolio-notes',title:'Portfolio direction',tag:'Creative',excerpt:'Show the work first. Let the writing explain the decisions.',body:'Open with a real project image instead of a long introduction. Each case study should answer: what needed to change, what I owned, and what the finished product does.\n\nKeep the navigation short. Give project images room to breathe. Use captions to explain the interesting detail, rather than adding another paragraph.',linked:'portfolio'}, {id:'dinner-notes',title:'Dinner, without the fuss',tag:'People',excerpt:'A shared table, something warm, and a manageable menu.',body:'Eight people is plenty. Make one main dish ahead of time and ask everyone to bring a small side or a drink.\n\nCheck dietary preferences before choosing the menu. Leave the evening open-ended; this is a chance to get to know each other.',linked:'dinner'}];
function Shell(){const navigate=useNavigate();const qc=useQueryClient();return <div className="demo-root"><div className="demo-notice"><span><span className="demo-dot"/>Interactive sample · fictional data · no live AI</span><button onClick={()=>{reset();qc.clear();navigate('/work');}}><RotateCcw size={12}/>Reset</button></div><div className="demo-layout"><aside className="demo-rail"><Link className="demo-brand" aria-label="Kora conversation" to="/kora"><KoraMark width={25} height={29}/><span>Kora</span></Link><nav aria-label="Sample workspaces">{[['/kora','Conversation',MessageSquare],['/work','Work',Target],['/brain','Brain',BookOpen]].map(([url,label,Icon]:any)=><NavLink key={url} to={url}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="demo-person"><span className="avatar">A</span><div>Alex Morgan<small>Sample workspace</small></div></div></aside><main className="demo-main"><ViewBarProvider><Routes><Route path="/work" element={<ProjectsWorkspace services={runtime as any} requestKey="portfolio" onAskKora={()=>navigate('/kora')}/>}/><Route path="/work/goals" element={<ProjectsWorkspace services={runtime as any} requestKey="portfolio" onAskKora={()=>navigate('/kora')}/>}/><Route path="/work/goals/:id" element={<Goal/>}/><Route path="/work/tasks/:id" element={<Task/>}/><Route path="/work/tasks" element={<AllTasks/>}/><Route path="/work/timeline" element={<AllTasks/>}/><Route path="/brain" element={<Brain/>}/><Route path="/brain/pages/:id" element={<Page/>}/><Route path="*" element={<Conversation/>}/></Routes></ViewBarProvider></main></div></div>}
function Goal(){const{id}=useParams();const goal=goals.find(g=>g.id===id);const[revision,setRevision]=useState(0);const qc=useQueryClient();if(!goal)return <div className="demo-page"><Link to="/work">Back to projects</Link></div>;return <article className="demo-page" key={id}><Link className="back" to="/work"><ArrowLeft size={14}/>All projects</Link><div className="demo-eyebrow">{goal.area||'Personal'} project</div><h1>{goal.title}</h1><p className="demo-lead">{goal.purposeMarkdown}</p><Badge tone="work" dot>{({active:'In progress',achieved:'Achieved',paused:'Paused',idea:'Idea',planned:'Planned'} as Record<string,string>)[goal.lifecycle]||goal.lifecycle}</Badge><section className="demo-section"><h2>Where things stand</h2><p>{goal.currentPositionMarkdown||'A fresh start. Add a next step below.'}</p></section><section className="demo-section"><div className="section-heading"><h2>Next steps</h2><span>Changes stay in this demo</span></div>{tasks.filter(t=>t.goalId===id).map(task=><div className="demo-task" key={task.id}><button className={'check '+(task.state==='completed'?'checked':'')} aria-label={(task.state==='completed'?'Reopen ':'Complete ')+task.title} aria-pressed={task.state==='completed'} onClick={()=>{task.state=task.state==='completed'?'planned':'completed';setRevision(revision+1);qc.invalidateQueries();}}>{task.state==='completed'&&<Check size={13}/>}</button><Link to={'/work/tasks/'+task.id}>{task.title}</Link><ChevronRight size={14}/></div>)}<AddTask goalId={id!} onAdd={()=>{setRevision(revision+1);qc.invalidateQueries();}}/></section><section className="demo-section"><h2>Connected knowledge</h2>{pages.filter(p=>p.linked===id).map(p=><Link className="demo-record" key={p.id} to={'/brain/pages/'+p.id}><FileText size={18}/><div><strong>{p.title}</strong><small>{p.excerpt}</small></div><ArrowUpRight size={16}/></Link>)}</section></article>}
function AddTask({goalId,onAdd}:{goalId:string,onAdd:()=>void}){const[value,setValue]=useState('');return <form className="add-task" onSubmit={e=>{e.preventDefault();if(value.trim()){tasks.push({id:crypto.randomUUID(),goalId,title:value.trim(),description:'Created in this sample workspace.',state:'planned'});setValue('');onAdd();}}}><input aria-label="New task" placeholder="Add a next step…" value={value} maxLength={160} onChange={e=>setValue(e.target.value)}/><Button type="submit" disabled={!value.trim()}><Plus size={14}/>Add</Button></form>}
function Task(){const{id}=useParams();const task=tasks.find(t=>t.id===id);const[done,setDone]=useState(task?.state==='completed');if(!task)return <AllTasks/>;return <article className="demo-page"><Link className="back" to={'/work/goals/'+task.goalId}><ArrowLeft size={14}/>Back to project</Link><div className="demo-eyebrow">Next step</div><h1>{task.title}</h1><p className="demo-lead">{task.description}</p><Button tone="primary" onClick={()=>{task.state=done?'planned':'completed';setDone(!done);}}><Check size={16}/>{done?'Completed — reopen':'Mark complete'}</Button></article>}
function AllTasks(){return <div className="demo-page"><div className="demo-eyebrow">Work</div><h1>Tasks</h1><p className="demo-lead">Small steps, connected to the bigger picture.</p>{tasks.map(t=><Link className="demo-record" to={'/work/tasks/'+t.id} key={t.id}><Check size={16}/><div><strong>{t.title}</strong><small>{goals.find(g=>g.id===t.goalId)?.title}</small></div><ChevronRight size={16}/></Link>)}</div>}
function Brain(){const[q,setQ]=useState('');return <div className="demo-page"><div className="demo-eyebrow">Brain</div><h1>A place for what matters.</h1><p className="demo-lead">Notes and knowledge, connected to the things Alex is working on.</p><label className="demo-search"><Search size={18}/><input aria-label="Search sample knowledge" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search this workspace…"/></label><div className="knowledge-grid">{pages.filter(p=>(p.title+p.body).toLowerCase().includes(q.toLowerCase())).map(p=><Link className="knowledge-card" key={p.id} to={'/brain/pages/'+p.id}><FileText size={22}/><span>{p.tag}</span><h2>{p.title}</h2><p>{p.excerpt}</p><small>Open note <ArrowUpRight size={14}/></small></Link>)}</div>{!pages.some(p=>(p.title+p.body).toLowerCase().includes(q.toLowerCase()))&&<p>No matching notes. Try “Lisbon” or “portfolio”.</p>}</div>}
function Page(){const{id}=useParams();const p=pages.find(p=>p.id===id);if(!p)return <Brain/>;return <article className="demo-page note"><Link className="back" to="/brain"><ArrowLeft size={14}/>All knowledge</Link><div className="demo-eyebrow">{p.tag} · Saved note</div><h1>{p.title}</h1>{p.body.split('\n\n').map((t,i)=><p key={i}>{t}</p>)}<section className="demo-section"><h2>Connected project</h2><Link className="demo-record" to={'/work/goals/'+p.linked}><Target size={18}/><strong>{goals.find(g=>g.id===p.linked)?.title}</strong><ArrowUpRight size={16}/></Link></section></article>}
function Conversation(){const[example,setExample]=useState<'trip'|'portfolio'>('trip');const[open,setOpen]=useState(false);return <article className="demo-conversation"><header><span className="demo-eyebrow">Prepared example</span><h1>{example==='trip'?'A little more room to wander.':'Make the work easy to see.'}</h1><p>Explore a prepared conversation, then open the records behind it.</p><div className="example-picker"><button aria-pressed={example==='trip'} onClick={()=>{setExample('trip');setOpen(false);}}>Plan the Lisbon trip</button><button aria-pressed={example==='portfolio'} onClick={()=>{setExample('portfolio');setOpen(false);}}>Review the portfolio</button></div></header><div className="user-message">{example==='trip'?'Can you help me settle the Lisbon plan? I want somewhere quiet, but I still want to walk everywhere.':'What should I focus on next for my portfolio? I want it to be simple and actually show my work.'}</div><div className="assistant-message"><KoraMark width={23} height={27}/><div><p>{example==='trip'?'Príncipe Real looks like the better fit. You saved it for the quieter streets and cafés, and it keeps the places you care about within walking distance.':'The homepage direction is the next useful decision. You already have the case-study drafts; now the first screen should show the work clearly.'}</p><button className="source-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}><BookOpen size={14}/>{open?'Hide connected context':'See connected context'}<ChevronRight size={13}/></button>{open&&<div className="context-card"><span>Prepared example · saved project + note</span><Link to={'/brain/pages/'+(example==='trip'?'lisbon-notes':'portfolio-notes')}>{example==='trip'?'Lisbon: where to stay':'Portfolio direction'}<ArrowUpRight size={13}/></Link><p>{example==='trip'?'Quiet neighborhood · under €150/night · flexible first day':'Real images first · concise writing · clear ownership'}</p></div>}<p>{example==='trip'?'I would keep arrival day light: check in, get coffee, and take a walk toward the river. The next decision is accommodation; the detailed itinerary can wait.':'Start with a real project image, then a short introduction. Once that feels right on a phone, export the remaining project images.'}</p><Link className="conversation-result" to={'/work/goals/'+(example==='trip'?'lisbon':'portfolio')}><Target size={18}/><div><strong>{example==='trip'?'A week in Lisbon':'Launch my design portfolio'}</strong><span>Open project and next steps</span></div><ArrowUpRight size={18}/></Link></div></div><footer className="demo-composer"><MessageSquare size={18}/><span>This sample uses a prepared conversation. Try Work or Brain to explore.</span></footer></article>}
const client=new QueryClient({defaultOptions:{queries:{retry:false,refetchOnWindowFocus:false}}});
createRoot(document.getElementById('root')!).render(<React.StrictMode><MotionConfig reducedMotion="user"><QueryClientProvider client={client}><HashRouter><TooltipProvider><ToastProvider><Shell/></ToastProvider></TooltipProvider></HashRouter></QueryClientProvider></MotionConfig></React.StrictMode>);
