// Fictional browser-only settings data. No credentials, daemon, scheduling or provider calls.
import type {NativeProvider,NativeSchedule,NativeNotification,NativeModelCatalog,NativeRuntimeCondition} from './upstream/lib/runtime';
const at='2026-09-13T12:00:00.000Z';
const unavailable=async(..._args:any[]):Promise<any>=>{throw Object.assign(new Error('This action requires the desktop app. The interactive sample does not connect accounts or execute external work.'),{code:'demo_external_action_unavailable',status:403});};
const providers:NativeProvider[]=['google-workspace','github','finance','wellbeing'].map(id=>({id,configured:false,accessState:'not_configured',connected:false,scopes:[],operations:[],health:'unavailable',unavailableReason:'Not connected in the interactive sample',connectionState:'not_configured',connectionObservedAt:at,supportedOperations:[],availableOperations:[],authorityObservation:{state:'not_observed'},updatedAt:at} as unknown as NativeProvider));
const catalog:NativeModelCatalog=[{id:'openai-codex',name:'OpenAI Codex',configured:false,entitlement:'unknown',authMethods:['oauth'],models:[{id:'gpt-5.6-sol',name:'GPT-5.6 Sol',input:['text','image'],reasoning:['low','medium','high']}]},{id:'anthropic',name:'Anthropic',configured:false,entitlement:'unknown',authMethods:['api-key'],models:[]}];
let quiet={quietStart:'22:00',quietEnd:'08:00',updatedAt:at,version:1,currentlyQuiet:false};
let schedules:NativeSchedule[]=[{id:'sample-weekly',name:'Weekly reflection',displayLabel:'Weekly reflection',prompt:'Review the week and prepare a short reflection from my saved projects. Fictional sample; no automatic execution.',trigger:{kind:'recurring',frequency:'weekly',localTime:'17:00',timezone:'America/New_York',startDate:'2026-09-13',weekdays:[0],interval:1},timezone:'America/New_York',nextDueAt:null,state:'paused',attentionTier:'digest',isTouchpoint:false,version:1,createdAt:at,updatedAt:at,lastRunState:null,lastRunId:null},{id:'sample-trip',name:'Lisbon packing reminder',displayLabel:'Lisbon packing reminder',prompt:'Review the packing note before the trip. Fictional paused schedule.',trigger:{kind:'once',at:'2026-10-11T14:00:00.000Z'},timezone:'America/New_York',nextDueAt:null,state:'paused',attentionTier:'interrupt',isTouchpoint:false,version:1,createdAt:at,updatedAt:at,lastRunState:null,lastRunId:null}];
const notices:NativeNotification[]=[{id:'sample-notice',sourceAttentionTier:'digest',sourceResultText:'The sample Lisbon notes are ready to explore.',type:'custom',title:'Your Lisbon notes',message:'Explore the fictional trip notes and connected project in this sample workspace.',scheduleId:null,runId:null,terminalRunId:null,sessionId:null,artifactId:null,createdAt:at,seenAt:null,idempotencyKey:'sample-notice'}];
const condition:NativeRuntimeCondition={observedAt:at,storage:{state:'ready',observedAt:at,integrity:'not_checked',lastCheckedAt:null,schemaVersion:1},model:{credentialState:'required'},integrations:{connected:0,needsAttention:0}};
const findSchedule=(id:string)=>{const s=schedules.find(s=>s.id===id);if(!s)throw new Error('Sample schedule not found');return s;};
export const settingsRuntime={
settingsOverview:async()=>({revision:1,items:[{section:'model',state:'unavailable',summary:'Interactive sample — no model connected',route:'/settings/model'},{section:'integrations',state:'normal',summary:'No accounts connected',route:'/settings/integrations'},{section:'schedules',state:'normal',summary:'Two paused sample schedules',route:'/settings/schedules'},{section:'background',state:'unavailable',summary:'Requires the Windows desktop app',route:'/settings/background'},{section:'notifications',state:'normal',summary:'Quiet hours: 10 PM–8 AM',route:'/settings/notifications'}]}),
providers:async()=>({providers}),checkProvider:unavailable,disconnectGoogleWorkspace:unavailable,githubAccounts:async()=>({accounts:[]}),disconnectGithub:unavailable,
startIntegrationAuth:unavailable,nextIntegrationAuth:unavailable,respondIntegrationAuth:unavailable,cancelIntegrationAuth:async()=>({cancelled:true}),
models:async()=>({providers:catalog}),selectModel:unavailable,startModelAuth:unavailable,nextModelAuth:unavailable,respondModelAuth:unavailable,cancelModelAuth:async()=>({cancelled:true}),
browserStatus:async()=>({state:'disconnected',reason:'The sample does not connect to a browser extension.'}),browserCredentials:async()=>({credentials:[],protectedStorageAvailable:false}),createBrowserCredential:unavailable,createOneTimeBrowserCredential:unavailable,deleteBrowserCredential:unavailable,
notificationSettings:async()=>({...quiet}),updateNotificationSettings:async(input:any)=>{quiet={...quiet,quietStart:input.start??null,quietEnd:input.end??null,version:quiet.version+1};return {...quiet};},
notifications:async(unseen=false)=>({notifications:notices.filter(n=>!unseen||!n.seenAt),complete:true,unseenCount:notices.filter(n=>!n.seenAt).length}),notification:async(id:string)=>({notification:notices.find(n=>n.id===id)??notices[0]}),markNotificationSeen:async(id:string)=>{const n=notices.find(n=>n.id===id)??notices[0];n.seenAt=at;return {notification:n};},markNotificationsSeenThrough:async()=>{let changed=0;for(const n of notices)if(!n.seenAt){n.seenAt=at;changed++;}return {changed,unseenCount:0};},
schedules:async(input:any={})=>({schedules:schedules.filter(s=>(!input.state||s.state===input.state)&&(!input.query||s.displayLabel.toLowerCase().includes(input.query.toLowerCase()))),complete:true}),schedule:async(id:string)=>({schedule:findSchedule(id)}),
createSchedule:async(input:any)=>{const schedule={...input,id:crypto.randomUUID(),name:input.name??null,displayLabel:input.name||input.prompt.slice(0,60),timezone:input.timezone??'America/New_York',nextDueAt:null,state:'paused',version:1,createdAt:at,updatedAt:at,lastRunState:null,lastRunId:null,isTouchpoint:input.isTouchpoint??false};schedules.push(schedule);return {schedule};},
updateSchedule:async(id:string,_version:number,input:any)=>{const s=findSchedule(id);Object.assign(s,input,{version:s.version+1,state:'paused'});return {schedule:s};},pauseSchedule:async(id:string)=>{const s=findSchedule(id);s.state='paused';s.version++;return {schedule:s};},resumeSchedule:unavailable,runSchedule:unavailable,cancelSchedule:async(id:string)=>{schedules=schedules.filter(s=>s.id!==id);return {cancelled:true};},
previewSchedule:async(trigger:any)=>({trigger,occurrences:trigger.kind==='once'?[trigger.at]:[],complete:trigger.kind==='once'}),scheduleRuns:async()=>({runs:[],complete:true}),scheduleRun:async()=>{throw new Error('This sample schedule has no live runs.');},
runtimeCondition:async()=>condition,checkLocalData:async()=>condition,backgroundStatus:async()=>({configured:false,healthy:false,taskName:'Desktop background process unavailable in browser sample'}),migrationSummary:async()=>({sources:[],pending:[]}),migrationPending:async()=>({items:[]}),dismissMigrationPending:async()=>({status:'gone'}),
capabilities:async()=>({groups:[],providers:providers.map(p=>({...p,connected:false,revocation:{supported:false}})),resources:{skills:0,prompts:0,diagnostics:0},limits:{maxToolsPerGroup:0,maxActiveGroups:0,maxActiveTools:0,maxSchemaCharactersPerGroup:0,maxActiveSchemaCharacters:0}}),
};
