import type {Goal, WorkItem, CalendarEvent, CalendarEventDraft, WorkConnectionSummary, WorkActivity, Project} from './upstream/lib/runtime';
const now=()=>new Date().toISOString();
const day=(offset:number)=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const clone=<T,>(v:T):T=>structuredClone(v);
const page=<T,>(items:T[])=>({items:clone(items),complete:true});
let goals:Goal[]=[];let tasks:WorkItem[]=[];let events:CalendarEvent[]=[];let deletedEvents:CalendarEvent[]=[];let connections:WorkConnectionSummary[]=[];let activity:WorkActivity[]=[];let focused=new Set(['project:lisbon','work_item:review']);let focusVersion=1;
const terminal=(s:string)=>['completed','cancelled','archived','achieved','stopped'].includes(s);
function need<T extends {id:string}>(items:T[],id:string):T{const r=items.find(x=>x.id===id);if(!r)throw new Error('This sample record is no longer available.');return r}
function log(type:string,id:string,operation:string,title:string){activity.unshift({id:crypto.randomUUID(),occurredAt:now(),operation,targetType:type,targetId:id,outcome:'settled',summary:`${operation}: ${title}`})}
function change<T extends {id:string;version:number;updatedAt:string}>(items:T[],id:string,v:number,patch:Partial<T>,type:string){const r=need(items,id);if(v!==undefined&&v!==r.version)throw new Error('The sample changed. Refresh and try again.');Object.assign(r,patch,{version:r.version+1,updatedAt:now()});log(type,id,'Updated',String((r as any).title));return {status:'settled' as const,record:clone(r),replayed:false}}
const project=(g:Goal):Project=>({...g,state:({idea:'planned',planned:'planned',active:'active',paused:'blocked',achieved:'completed',stopped:'cancelled',archived:'archived'} as any)[g.lifecycle],startDate:g.plannedStart,blocker:g.pauseReason});
const focus=(type:string,id:string)=>({inUserAttention:focused.has(`${type}:${id}`),capacity:{state:'undisclosed' as const}});
const outline=(id:string,mode='current')=>({nodes:tasks.filter(t=>t.goalId===id&&!t.parentWorkItemId&&(mode==='terminal'?terminal(t.state):!terminal(t.state))).map(item=>({item:clone(item),children:page(tasks.filter(t=>t.parentWorkItemId===item.id&&(mode==='terminal'?terminal(t.state):!terminal(t.state))))})),complete:true});
const workspace=(id:string)=>({goal:clone(need(goals,id)),focus:focus('project',id),work:outline(id),connections:page(connections.filter(c=>c.from.id===id)),activity:page(activity.filter(a=>a.targetId===id))});
const active=()=>({version:focusVersion,records:[...goals.filter(g=>focused.has(`project:${g.id}`)).map(g=>({...project(g),target:{type:'project',id:g.id},nextActions:clone(tasks.filter(t=>t.goalId===g.id&&!terminal(t.state)))})),...tasks.filter(t=>focused.has(`work_item:${t.id}`)).map(t=>({...clone(t),target:{type:'work_item',id:t.id},nextActions:[]}))],capacity:{state:'undisclosed' as const}});
function eventFrom(d:CalendarEventDraft,id:string=crypto.randomUUID()):CalendarEvent{return {...d,eventId:id,providerId:'kora',authority:'kora',allDay:d.start.kind==='date',viewerTimeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,status:'confirmed',availability:d.availability??'busy',attendees:(d.attendees??[]).map(a=>({...a,organizer:false,self:false,optional:a.optional??false,responseStatus:'needsAction'})),recurrence:d.recurrence??[],conference:undefined,createdAt:now(),updatedAt:now(),revision:'1',syncState:'local',capabilities:{readable:true,writable:true,deletable:true,manageAttendees:false,editSeries:false,editOccurrence:false}}}
export function resetWorkCalendarFixture(){
 const common={shape:'finish' as const,priority:2,sensitivity:'private' as const,provenance:'synthetic_demo',version:1,createdAt:now(),updatedAt:now()};
 goals=[{...common,id:'lisbon',title:'A week in Lisbon',area:'Travel',purposeMarkdown:'Find a quiet, walkable base and leave room to wander.',currentPositionMarkdown:'Príncipe Real and Graça are shortlisted. Choose accommodation before filling the itinerary.',lifecycle:'active',targetDate:day(29)}, {...common,id:'portfolio',title:'Launch my design portfolio',area:'Creative',purposeMarkdown:'Give three finished projects a thoughtful home.',currentPositionMarkdown:'Case studies are drafted. Reviewing the first screen and collecting project images.',lifecycle:'active',targetDate:day(14)}, {...common,id:'dinner',title:'Host a neighborhood dinner',area:'People',purposeMarkdown:'Bring a few neighbors together over a simple meal.',currentPositionMarkdown:'Eight guests; ask about dates and dietary preferences.',lifecycle:'planned',targetDate:day(20)}, {...common,id:'reading',title:'Make space for reading',area:'Personal',purposeMarkdown:'Finish a book and save the ideas worth returning to.',lifecycle:'achieved',resultMarkdown:'Finished the book and collected reading notes.',achievedAt:now()}, {...common,id:'garden',title:'Grow a balcony herb garden',area:'Home',purposeMarkdown:'A few fresh herbs for weeknight cooking.',lifecycle:'paused',pauseReason:'Waiting for replacement planters.'}];
 const base={kind:'task' as const,priority:2,provenance:'synthetic_demo',version:1,createdAt:now(),updatedAt:now()};
 tasks=[{...base,id:'stay',goalId:'lisbon',title:'Choose a place to stay',descriptionMarkdown:'Compare saved options in Príncipe Real and Graça. Aim for under €150 per night.',state:'active',dueAt:day(2)},{...base,id:'flights',goalId:'lisbon',title:'Save flight details',descriptionMarkdown:'Arrival and departure are saved in the trip notes.',state:'completed',completedAt:now()},{...base,id:'route',goalId:'lisbon',title:'Plan a first-day walk',state:'planned',dueAt:day(8)},{...base,id:'review',goalId:'portfolio',title:'Review the homepage direction',descriptionMarkdown:'Check the first screen on a phone and trim the introduction.',state:'active',dueAt:day(0)},{...base,id:'images',goalId:'portfolio',title:'Export project images',state:'planned',dueAt:day(3)},{...base,id:'date',goalId:'dinner',title:'Choose a date with the neighbors',state:'planned',dueAt:day(4)},{...base,id:'planters',goalId:'garden',title:'Collect replacement planters',state:'blocked',blocker:'The shop is waiting on its next delivery.'},{...base,id:'return-book',title:'Return the library book',area:'Personal',state:'planned',dueAt:day(1)},{...base,id:'old-note',title:'File last month’s travel receipts',state:'archived',archivedAt:now()}];
 events=[['portfolio-review','Portfolio direction review',0,14,'Review the homepage and shortlist project images.'],['coffee','Coffee with Maya',1,10,'A catch-up at the neighborhood café.'],['trip-planning','Lisbon planning',2,18,'Compare accommodation and keep the first day light.'],['market','Neighborhood market',4,11,'Pick up vegetables and herbs.']].map(([id,title,offset,hour,description])=>eventFrom({calendarId:'kora:personal',title:String(title),description:String(description),start:{kind:'dateTime',instant:`${day(Number(offset))}T${hour}:00:00Z`,timeZone:'UTC'},end:{kind:'dateTime',instant:`${day(Number(offset))}T${Number(hour)+1}:00:00Z`,timeZone:'UTC'},conference:{kind:'none'}},String(id)));
 deletedEvents=[];connections=[];activity=goals.map(g=>({id:`created-${g.id}`,occurredAt:now(),operation:'Created',targetType:'project',targetId:g.id,outcome:'settled',summary:`Created ${g.title}`}));focused=new Set(['project:lisbon','work_item:review']);focusVersion=1;
}
resetWorkCalendarFixture();
export function getWorkCalendarSnapshot(){return clone({goals,tasks,events});}
function goalPage(input:any={}){return {...page(goals.filter(g=>(input.includeArchived||g.lifecycle!=='archived')&&(input.filter==='terminal'?terminal(g.lifecycle):!input.filter||input.filter==='open'?!terminal(g.lifecycle):g.lifecycle===input.filter)&&(!input.area||g.area===input.area)&&(!input.query||`${g.title} ${g.area} ${g.purposeMarkdown}`.toLowerCase().includes(input.query.toLowerCase()))).map(goal=>({goal,visibleOpenWorkItemCount:tasks.filter(t=>t.goalId===goal.id&&!terminal(t.state)).length,visibleBlockedWorkItemCount:tasks.filter(t=>t.goalId===goal.id&&t.state==='blocked').length,visibleOverdueWorkItemCount:tasks.filter(t=>t.goalId===goal.id&&!terminal(t.state)&&t.dueAt&&t.dueAt<day(0)).length,nextOpenWorkItem:tasks.find(t=>t.goalId===goal.id&&!terminal(t.state)),inUserAttention:focused.has(`project:${goal.id}`)}))),coverage:{state:'complete'}}}
function createItem(id:string,input:any){const item={...input.item,id:crypto.randomUUID(),goalId:id||input.item.goalId,projectId:id||input.item.goalId,provenance:'synthetic_demo',version:1,createdAt:now(),updatedAt:now()};tasks.push(item);log('work_item',item.id,'Created',item.title);return {status:'settled',record:clone(item),replayed:false}}
export const workCalendarRuntime={
 goalsPage:async(input:any={})=>goalPage(input),
 goal:async(id:string)=>({goal:clone(need(goals,id))}),goalWorkspace:async(id:string)=>workspace(id),goalOutline:async(id:string,mode='current')=>outline(id,mode),
 createGoal:async({goal}:any)=>{const g={...goal,id:crypto.randomUUID(),sensitivity:goal.sensitivity??'private',version:1,createdAt:now(),updatedAt:now()};goals.push(g);log('project',g.id,'Created',g.title);return {status:'settled',record:clone(g),replayed:false}},
 updateGoal:async(id:string,v:number,changes:any)=>change(goals,id,v,changes,'project'),achieveGoal:async(id:string,v:number,resultMarkdown:string)=>change(goals,id,v,{lifecycle:'achieved',resultMarkdown,achievedAt:now()},'project'),stopGoal:async(id:string,v:number,reason:string)=>change(goals,id,v,{lifecycle:'stopped',stopReason:reason,stoppedAt:now()},'project'),resumeGoal:async(id:string,v:number,lifecycle:any,reason:string)=>change(goals,id,v,{lifecycle,resumeReason:reason,resumedAt:now(),archivedAt:undefined,achievedAt:undefined,stoppedAt:undefined},'project'),archiveGoal:async(id:string,v:number)=>change(goals,id,v,{lifecycle:'archived',archivedAt:now()},'project'),
 projectsPage:async(input:any={})=>{const p=goalPage(input);return {...p,items:p.items.map(({goal,...rest})=>({...rest,project:project(goal)}))}},project:async(id:string)=>({project:project(need(goals,id))}),projectWorkspace:async(id:string)=>{const {goal,...rest}=workspace(id);return {...rest,project:project(goal)}},projectOutline:async(id:string,mode='current')=>outline(id,mode),
 createGoalWorkItem:async(id:string,input:any)=>createItem(id,input),createProjectWorkItem:async(id:string,input:any)=>createItem(id,input),
 workItems:async(input:any={})=>page(tasks.filter(t=>(input.filter==='terminal'?terminal(t.state)&&t.state!=='archived':input.filter==='archived'?t.state==='archived':!input.filter||input.filter==='open'?!terminal(t.state):t.state===input.filter)&&(!input.kind||t.kind===input.kind)&&(!(input.goalId||input.projectId)||t.goalId===(input.goalId||input.projectId))&&(!input.area||t.area===input.area)&&(!input.query||`${t.title} ${t.descriptionMarkdown??''}`.toLowerCase().includes(input.query.toLowerCase()))).map(item=>({item,goal:goals.find(g=>g.id===item.goalId),inUserAttention:focused.has(`work_item:${item.id}`)}))),
 workItem:async(id:string)=>({item:clone(need(tasks,id))}),workItemWorkspace:async(id:string)=>{const item=need(tasks,id);return {item:clone(item),goal:clone(goals.find(g=>g.id===item.goalId)),parent:clone(tasks.find(t=>t.id===item.parentWorkItemId)),children:page(tasks.filter(t=>t.parentWorkItemId===id)),focus:focus('work_item',id),connections:page(connections.filter(c=>c.from.id===id)),activity:page(activity.filter(a=>a.targetId===id))}},workItemChildren:async(id:string)=>page(tasks.filter(t=>t.parentWorkItemId===id)),
 updateWorkItem:async(id:string,v:number,changes:any)=>change(tasks,id,v,changes,'work_item'),completeWorkItem:async(id:string,v:number,resultMarkdown:string)=>change(tasks,id,v,{state:'completed',resultMarkdown,completedAt:now()},'work_item'),cancelWorkItem:async(id:string,v:number,reason:string)=>change(tasks,id,v,{state:'cancelled',cancellationReason:reason,cancelledAt:now()},'work_item'),reactivateWorkItem:async(id:string,v:number,state:any,reason:string)=>change(tasks,id,v,{state,reactivationReason:reason,reactivatedAt:now(),archivedAt:undefined,completedAt:undefined,cancelledAt:undefined},'work_item'),archiveWorkItem:async(id:string,v:number)=>change(tasks,id,v,{state:'archived',archivedAt:now()},'work_item'),
 activeWork:async()=>active(),addWorkFocus:async(target:any)=>{focused.add(`${target.type}:${target.id}`);focusVersion++;return {status:'settled',activeWork:active(),replayed:false}},removeWorkFocus:async(target:any)=>{focused.delete(`${target.type}:${target.id}`);focusVersion++;return {status:'settled',activeWork:active(),replayed:false}},
 searchWork:async(query:string,_mode?:string,recordTypes=['project','work_item'])=>({results:[...(recordTypes.includes('project')?goals.map(g=>({recordType:'project',record:project(g)})):[]),...(recordTypes.includes('work_item')?tasks.map(record=>({recordType:'work_item',record})):[])].filter(x=>x.record.title.toLowerCase().includes(query.toLowerCase())),complete:true}),searchWorkPeople:async(query:string)=>({results:[{id:'maya',displayName:'Maya Chen',relationship:'Friend',version:1}].filter(p=>p.displayName.toLowerCase().includes(query.toLowerCase())),complete:true}),
 workActivity:async(_type:string,id:string)=>page(activity.filter(a=>a.targetId===id)),workConnections:async({id}:any)=>page(connections.filter(c=>c.from.id===id)),createWorkConnection:async(input:any)=>{const connection={id:crypto.randomUUID(),from:input.from,relation:input.relation,target:input.target,label:input.target.id,availability:'available' as const,createdAt:now()};connections.push(connection);return {status:'settled',connection:clone(connection),replayed:false}},unlinkWorkConnection:async(id:string)=>{connections=connections.filter(c=>c.id!==id);return {status:'settled',id,deleted:true,replayed:false}},deleteWorkRecord:async(surface:string,id:string)=>{if(surface==='project'){goals=goals.filter(g=>g.id!==id);tasks=tasks.filter(t=>t.goalId!==id)}else tasks=tasks.filter(t=>t.id!==id);return {status:'settled',deletion:{surface,id,deleted:true,negativeRead:true,erased:[id],independentSources:[]},replayed:false}},
 issueCalendarContextReference:async(input:any)=>({selection:{state:'available',authorization:'allowed',selectionId:crypto.randomUUID(),evidenceHandle:'sample-calendar-context',display:{objectKind:input.kind==='event'?'calendar_event':'calendar_query',title:input.title??events.find(e=>e.eventId===input.eventId)?.title??'Sample calendar'},expiresAt:new Date(Date.now()+3600000).toISOString()}}),
 calendarSources:async()=>({sources:[{calendarId:'kora:personal',name:'Personal',providerId:'kora',authority:'kora',primary:true,selected:true,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,color:'#66816a',accessRole:'owner',writable:true,status:'available',syncState:'local'}],complete:true,status:{state:'available'}}),
 calendarEvents:async(input:any)=>({events:clone(events.filter(e=>input.calendarIds.includes(e.calendarId)&&Date.parse(e.start.kind==='date'?e.start.date:e.start.instant)<Date.parse(input.end)&&Date.parse(e.end.kind==='date'?e.end.date:e.end.instant)>Date.parse(input.start)).map(e=>({...e,viewerTimeZone:input.viewerTimeZone}))),range:{start:input.start,end:input.end},complete:true,status:{state:'available'},sourceErrors:[]}),calendarEvent:async(calendarId:string,id:string,viewerTimeZone:string)=>{const e=events.find(e=>e.calendarId===calendarId&&e.eventId===id);if(!e)throw new Error('Sample event not found');return {event:clone({...e,viewerTimeZone}),status:{state:'available'}}},
 createCalendarEvent:async({event}:any)=>{const e=eventFrom(event);events.push(e);return {status:'acknowledged',operationId:crypto.randomUUID(),event:clone(e)}},updateCalendarEvent:async(calendarId:string,id:string,{patch}:any)=>{const e=events.find(e=>e.calendarId===calendarId&&e.eventId===id);if(!e)throw new Error('Sample event not found');Object.assign(e,patch,{allDay:(patch.start??e.start).kind==='date',updatedAt:now(),revision:String(Number(e.revision??0)+1)});return {status:'acknowledged',operationId:crypto.randomUUID(),event:clone(e)}},deleteCalendarEvent:async(calendarId:string,id:string)=>{const e=events.find(e=>e.calendarId===calendarId&&e.eventId===id);if(!e)throw new Error('Sample event not found');deletedEvents.push(e);events=events.filter(e=>e.eventId!==id);return {status:'acknowledged',operationId:crypto.randomUUID(),recovery:{kind:'restore_local_calendar_event',calendarId,eventId:id,deletedRevision:e.revision}}},restoreCalendarEvent:async(_calendarId:string,id:string)=>{const e=deletedEvents.find(e=>e.eventId===id);if(!e)throw new Error('Sample event not found');events.push(e);deletedEvents=deletedEvents.filter(e=>e.eventId!==id);return {status:'acknowledged',operationId:crypto.randomUUID(),event:clone(e)}},calendarFreeBusy:async(input:any)=>({calendars:Object.fromEntries(input.calendarIds.map((id:string)=>[id,{busy:events.filter(e=>e.calendarId===id&&e.availability==='busy'&&Date.parse(e.start.kind==='date'?e.start.date:e.start.instant)<Date.parse(input.end)&&Date.parse(e.end.kind==='date'?e.end.date:e.end.instant)>Date.parse(input.start)).map(e=>({start:e.start.kind==='date'?e.start.date:e.start.instant,end:e.end.kind==='date'?e.end.date:e.end.instant})),errors:[]}])),status:{state:'available'}})
};
